[package]
name = "conway-piston"
version = "0.1.0"
authors = ["honorabrutroll <edward.yang6771@gmail.com>"]
[dependencies] 
piston = "*"
pistoncore-glutin_window = "*"
piston2d-graphics = "*"
piston2d-opengl_graphics = "*"
rand = "*"
num_cpus = "*"
