[package]
name = "conway-piston"
version = "0.1.3"
authors = ["honorabrutroll <edward.yang6771@gmail.com>"]
[dependencies] 
piston = "0.10.1"
pistoncore-glutin_window = "0.12.0"
piston2d-graphics = "0.8.0"
piston2d-opengl_graphics = "0.10.0"
rand = "0.3.11"
num_cpus = "0.2.6"
clap = "1.4.0"
